// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsmU7jOynauShXnxOT7d8-J73AvAbWO7A',
    appId: '1:586962012567:web:95acf7163192e8370a5cd2',
    messagingSenderId: '586962012567',
    projectId: 'elearning12-8e8f2',
    authDomain: 'elearning12-8e8f2.firebaseapp.com',
    storageBucket: 'elearning12-8e8f2.firebasestorage.app',
    measurementId: 'G-CTZ56MEFM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUJ6K0iHp6TD8wnRpJNPBBdL5HCOz2eaA',
    appId: '1:586962012567:android:984349158ae86ef60a5cd2',
    messagingSenderId: '586962012567',
    projectId: 'elearning12-8e8f2',
    storageBucket: 'elearning12-8e8f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRvzrHBG5dCfM3VIyFa1zjnJFhAGxK4DU',
    appId: '1:586962012567:ios:41ecf74362dc6c800a5cd2',
    messagingSenderId: '586962012567',
    projectId: 'elearning12-8e8f2',
    storageBucket: 'elearning12-8e8f2.firebasestorage.app',
    iosBundleId: 'com.example.cloudStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRvzrHBG5dCfM3VIyFa1zjnJFhAGxK4DU',
    appId: '1:586962012567:ios:41ecf74362dc6c800a5cd2',
    messagingSenderId: '586962012567',
    projectId: 'elearning12-8e8f2',
    storageBucket: 'elearning12-8e8f2.firebasestorage.app',
    iosBundleId: 'com.example.cloudStorage',
  );
}
